<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://zeroz-lab.github.io</id>
    <title>ZeroZ-Lab</title>
    <updated>2020-12-29T03:03:00.267Z</updated>
    <generator>https://github.com/jpmonette/feed</generator>
    <link rel="alternate" href="https://zeroz-lab.github.io"/>
    <link rel="self" href="https://zeroz-lab.github.io/atom.xml"/>
    <subtitle>What i cannot create i do not understand</subtitle>
    <logo>https://zeroz-lab.github.io/images/avatar.png</logo>
    <icon>https://zeroz-lab.github.io/favicon.ico</icon>
    <rights>All rights reserved 2020, ZeroZ-Lab</rights>
    <entry>
        <title type="html"><![CDATA[Promise使用、实现与扩展]]></title>
        <id>https://zeroz-lab.github.io/post/promise-shi-yong-shi-xian-yu-kuo-zhan/</id>
        <link href="https://zeroz-lab.github.io/post/promise-shi-yong-shi-xian-yu-kuo-zhan/">
        </link>
        <updated>2020-12-28T14:50:20.000Z</updated>
        <summary type="html"><![CDATA[<p>Promise是处理JavaScript异步代码的一种方式，本文通过使用、实现与扩展三个方面完整介绍Promise。</p>
]]></summary>
        <content type="html"><![CDATA[<p>Promise是处理JavaScript异步代码的一种方式，本文通过使用、实现与扩展三个方面完整介绍Promise。</p>
<!-- more -->
<h2 id="介绍">介绍</h2>
<p>promise是一个代理对象，当代理的值被创建时可能时未知的。它允许你为异步操作的成功或者失败分别绑定相应的处理方法。</p>
<p>这样异步代码就可以像同步方法一样返回值。</p>
<p>一个Promise包含三个状态</p>
<ol>
<li>pending：初始状态</li>
<li>fulfilled：成功</li>
<li>rejected：失败</li>
<li>Settled: 已经成功或失败的</li>
</ol>
<figure data-type="image" tabindex="1"><img src="https://zeroz-lab.github.io/post-images/1609167068582.png" alt="" loading="lazy"></figure>
<h2 id="重要规则">重要规则</h2>
<p>标准的promise是由Promises/A+规定的。目前已经有很多符合标准的实现，包括JavaScript标准的Promise。</p>
<p>Promises 必须符合以下规则：</p>
<ul>
<li>一个promise或者&quot;thenable&quot;是一个对象提供符合标准的<code>.then()</code>方法。</li>
<li>一个<code>pending</code>状态的promise 可以转变为<code>fullfilled</code>或者<code>rejected</code>状态</li>
<li>一个<code>fullfilled</code>或者<code>rejected</code>的promise是<code>settled</code>，而且不能转变为其他状态</li>
<li>一旦一个promise被设置为<code>settled</code>，它必然包含一个值（可能是<code>undefined</code>）。这个值不能被改变。</li>
</ul>
<h2 id="链式调用">链式调用</h2>
<p>由于<code>.then()</code>总是会返回一个新的promise，就可以采用链式调用，从而精确的控制如何还有在何处处理错误。Promises允许你可以模拟正常的同步代码，使用<code>try/catch</code>行为</p>
<p>就像同步代码，链式调用会产生序列，以串行的方式运行.</p>
<pre><code class="language-javascript">fetch(url)
  .then(process)
  .then(save)
  .catch(handleErrors)
;
</code></pre>
<p>下面时一个比价复杂的例子</p>
<!-- more -->
<pre><code class="language-javascript">const wait = time =&gt; new Promise(
  res =&gt; setTimeout(() =&gt; res(), time)
);

wait(200)
  // onFulfilled() can return a new promise, `x`
  .then(() =&gt; new Promise(res =&gt; res('foo')))
  // the next promise will assume the state of `x`
  .then(a =&gt; a)
  // Above we returned the unwrapped value of `x`
  // so `.then()` above returns a fulfilled promise
  // with that value:
  .then(b =&gt; console.log(b)) // 'foo'
  // Note that `null` is a valid promise value:
  .then(() =&gt; null)
  .then(c =&gt; console.log(c)) // null
  // The following error is not reported yet:
  .then(() =&gt; {throw new Error('foo');})
  // Instead, the returned promise is rejected
  // with the error as the reason:
  .then(
    // Nothing is logged here due to the error above:
    d =&gt; console.log(`d: ${ d }`),
    // Now we handle the error (rejection reason)
    e =&gt; console.log(e)) // [Error: foo]
  // With the previous exception handled, we can continue:
  .then(f =&gt; console.log(`f: ${ f }`)) // f: undefined
  // The following doesn't log. e was already handled,
  // so this handler doesn't get called:
  .catch(e =&gt; console.log(e))
  .then(() =&gt; { throw new Error('bar'); })
  // When a promise is rejected, success handlers get skipped.
  // Nothing logs here because of the 'bar' exception:
  .then(g =&gt; console.log(`g: ${ g }`))
  .catch(h =&gt; console.log(h)) // [Error: bar]
;
</code></pre>
<h2 id="错误捕捉">错误捕捉</h2>
<p>Promises既有成功的回调也有失败的回调，以下代码很常见</p>
<pre><code class="language-javascript">save().then(
  handleSuccess,
  handleError
);
</code></pre>
<p>但是，如果在<code>handleSuccess</code>中抛出错误如何？这个promise从<code>.then()</code>返回会被拒绝，但是没有被抓住，这意味着这个错误被吞噬了。</p>
<p>因此，有些人认为上面的代码是反模式，建议以下代码：</p>
<pre><code class="language-javascript">save()
  .then(handleSuccess)
  .catch(handleError)
;
</code></pre>
<p>这种区别虽然微妙，但是很重要。在第一个例子中，在<code>save()</code>中的错误会被捕获，但是在<code>handleSuccess()</code>函数中的会被吞噬。</p>
<figure data-type="image" tabindex="2"><img src="https://zeroz-lab.github.io/post-images/1609167122688.png" alt="" loading="lazy"></figure>
<p>在第二个例子中，<code>.catch()</code>将会捕获来自<code>save()</code>和<code>handleSuccess()</code>中的错误。</p>
<figure data-type="image" tabindex="3"><img src="https://zeroz-lab.github.io/post-images/1609167133005.png" alt="" loading="lazy"></figure>
<p>当然，在<code>save()</code>中的错误可能是网络错，而在<code>handleSuccess()</code>中的错误可能是开发者忘记捕获特定的状态码，你可以以不同方式同时处理他们。</p>
<pre><code class="language-javascript">save()
  .then(
    handleSuccess,
    handleNetworkError
  )
  .catch(handleProgrammerError)
;
</code></pre>
<p>但是，还是强烈建议在调用链最后使用<code>.catch()</code></p>
<h2 id="构造函数">构造函数</h2>
<p>Promise():创建一个<code>Promise</code>对象。</p>
<pre><code class="language-javascript">const promise1 = new Promise((resolve,reject)=&gt;{
	// ......
})
</code></pre>
<h2 id="静态方法">静态方法</h2>
<h3 id="promisealliterable">Promise.all(iterable)</h3>
<p><code>Promise.all()</code>方法接受一个promise的iterable类型(Array,Map,Set )的输入，并且返回一个<code>Promise</code>对象。</p>
<p>返回的res为一个数组</p>
<h3 id="promiseallsettled">Promise.allSettled()</h3>
<p>该<code>Promise.allSettled()</code>方法返回一个在所有给定的promise都已经fulfilled或rejected后的promise，并带有一个对象数组，每个对象表示对应的promise结果。</p>
<h3 id="promiseany">Promise.any()</h3>
<p>接受一个<code>promise</code>的<code>iterable</code>类型的输入，只要其中一个promise成功，就返回那个已经成功的promise。如果可迭代对象没有一个promise成功，就返回一个失败的promise和<a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/AggregateError">AggregateError</a>类型的实例，他是Error的一个子类,用以把单一的错误集合在一起。</p>
<h3 id="promiserace">Promise.race()</h3>
<p><code>Promise.race()</code>方法返回可迭代promise中返回最快的的成功或者失败，</p>
<h3 id="promiseresolve">Promise.resolve()</h3>
<p><code>Promise.resolve(reason)</code>直接返回一个promise，并带有<code>reason</code>值。</p>
<h3 id="promisereject">Promise.reject()</h3>
<p><code>Promise.reject(value)</code>直接返回一个promise，并带有一个拒绝值。</p>
<h2 id="实例方法">实例方法</h2>
<h3 id="promiseprototypecatch">Promise.prototype.catch()</h3>
<p>参考前面错误捕捉，捕获错误使用</p>
<h3 id="promiseprototypethen">Promise.prototype.then()</h3>
<p>参考前面链式调用。</p>
<h3 id="promiseprototypefinally">Promise.prototype.finally()</h3>
<p><code>finally()</code>返回一个promise，无论fullfilled或者rejected，都会执行指定的回调函数。</p>
]]></content>
    </entry>
    <entry>
        <title type="html"><![CDATA[✏️小抄：请求并发控制]]></title>
        <id>https://zeroz-lab.github.io/post/qing-qiu-bing-fa-kong-zhi/</id>
        <link href="https://zeroz-lab.github.io/post/qing-qiu-bing-fa-kong-zhi/">
        </link>
        <updated>2020-12-28T02:25:28.000Z</updated>
        <summary type="html"><![CDATA[<p>请求并发控制</p>
]]></summary>
        <content type="html"><![CDATA[<p>请求并发控制</p>
<!-- more -->
]]></content>
    </entry>
</feed>